[package]
name = "crier"
version = "0.2.1"
edition = "2021"
description = "Simple push notification tool"

[dependencies]
clap = { version = "4", features = ["derive"] }
rumqttc = "0.25"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
dirs = "5"
